# Generated by Django 6.0 on 2026-01-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=300)),
                ('venue_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=100)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('business', 'Business'), ('health', 'Health & Wellness'), ('education', 'Education'), ('arts', 'Arts & Culture'), ('sports', 'Sports & Fitness'), ('food', 'Food & Drink'), ('music', 'Music'), ('other', 'Other')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['date', 'category'], name='events_even_date_9c0155_idx'), models.Index(fields=['city', 'country'], name='events_even_city_8bb2fa_idx')],
            },
        ),
    ]
