# Generated by Django 6.0 on 2026-01-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('speaker_name', models.CharField(blank=True, help_text='Name of the speaker if not a registered user', max_length=200)),
                ('speaker_bio', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, help_text='e.g., Room A, Main Hall', max_length=100)),
                ('track', models.CharField(blank=True, help_text='e.g., Technical, Business', max_length=100)),
                ('topics', models.TextField(blank=True, help_text='Comma separated topics')),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='events.event')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time', 'room'],
                'indexes': [models.Index(fields=['event', 'start_time'], name='event_sessi_event_i_64f0df_idx')],
            },
        ),
    ]
